### ISSUE TITLE
Centos 6.8 deployment error at "init secondary instance"

### ISSUE THREAD

**Issue by markotitel** [sergevs/ansible-cloudera-hadoop#8] opened 2017-04-28 16:39 UTC
[hosts.txt](https://github.com/sergevs/ansible-cloudera-hadoop/files/965019/hosts.txt)

Thanks for this nicely written playbook.

I am trying to provision this on single machine.

my hosts file is attached.

I have added this repo https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/cloudera-cdh5.repo

Installed Java.

And provisioned like this.

ansible-cloudera-hadoop]# ansible-playbook -i hosts site.yaml --connection=local --become

The error I get is quite long this is interesting part

TASK [hadoop : init secondary instance] ****************************************
fatal: [localhost]: FAILED! =>

INFO namenode.NameNode: registered UNIX signal handlers for [TERM, HUP, INT]\n17/04/28 18:37:43 INFO namenode.NameNode: createNameNode [-bootstrapStandby]\n17/04/28 18:37:43 ERROR namenode.NameNode: Failed to start namenode.\njava.io.IOException: org.apache.hadoop.HadoopIllegalArgumentException: HA is not enabled for this namenode.

**Comment by sergevs** [comment] 2017-04-30 11:46
could you please provide the ansible version you are using and share full log - as an instance you can put it in gist and provide me the link

**Comment by sergevs** [comment] 2017-05-10 10:27
I've reproduced the issue. The problem is related to **localhost** you are using in the playbook **hosts** file.
The playbook relays on  the hostname and proper hostname resolving which is not available for the configuration.
You have to use the **hostname** in hosts file, see output:
`ansible -i hosts localhost --connection=local --become -msetup | grep ansible_hostname` 
If the **hostname** is not resolving, you can add appropriate entry to /etc/hosts file.

**Closed as completed by sergevs** 2017-05-10 10:27 UTC
